/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a4_Projects.project6__5_23.app.src.test.java.project6;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
